name: quiz_app
description: A new Flutter project.


version: 2.0.1+8

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_messaging: ^14.6.1
  google_sign_in: ^6.1.0
  google_mobile_ads: ^3.0.0
  firebase_analytics: ^10.4.1
  firebase_storage: ^11.2.1
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.6
  rounded_loading_button: ^2.1.0
  provider: ^6.0.5
  loading_indicator: ^3.1.0
  flutter_html: ^3.0.0-beta.1
  cached_network_image: ^3.2.3
  salomon_bottom_bar: ^3.3.2
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  pod_player: ^0.2.1
  flutter_timer_countdown: ^1.0.5
  percent_indicator: ^4.2.3
  hive: ^2.2.3
  html_unescape: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  line_icons: ^2.0.1
  ionicons: ^0.2.1
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.1
  launch_review: ^3.0.1
  flutter_web_browser: ^0.17.1
  flutter_facebook_auth: ^6.0.1
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3
  package_info_plus: ^4.1.0
  material_dialogs: ^1.1.4
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.2
  auto_animated: ^3.1.0
  delayed_display: ^2.0.0
  easy_localization: ^3.0.2
  lottie: ^2.3.2
  flutter_staggered_animations: ^1.1.1
  simple_animations: ^5.0.0+3
  app_settings: ^4.1.8
  image_picker: ^0.8.7+5
  soundpool: ^2.3.0
  in_app_purchase: ^3.1.5
  just_audio: ^0.9.33
  quiver: ^3.2.1
  auto_size_text: ^3.0.0


# dependency_overrides:
#   intl: ^0.18.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/user_avatars/
    - assets/animations/
    - assets/translations/
    - assets/sounds/


  fonts:

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500


